=== 8biz/champ/protocol/ruleset-rev01.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CHAMP Ruleset",
  "type": "object",
  "required": [
    "metadata",
    "periodTimesInSeconds",
    "periodTimeCountingDirection",
    "periodBreakTimeInSeconds",
    "injuryTimeWithoutBloodInSeconds",
    "injuryTimeWithBloodInSeconds",
    "injuryTimeCountingDirection",
    "victoryTypes"
  ],
  "properties": {
    "metadata": {
      "type": "object",
      "required": ["name","description","languages","author"],
      "properties": {
        "name": { "type": "string" },
        "description": { "type": "string" },
        "version": { "type": "string" },
        "languages": { "type": "array", "items": { "type": "string" } },
        "author": { "type": "string" }
      },
      "additionalProperties": false
    },
    "periodTimesInSeconds": {
      "type": "array",
      "minItems": 1,
      "items": { "type": "integer", "minimum": 0 }
    },
    "periodTimeCountingDirection": {
      "type": "string",
      "enum": ["Up","Down"]
    },
    "periodBreakTimeInSeconds": { "type": "integer", "minimum": 0 },
    "injuryTimeWithoutBloodInSeconds": { "type": "integer", "minimum": 0 },
    "injuryTimeWithBloodInSeconds": { "type": "integer", "minimum": 0 },
    "injuryTimeCountingDirection": {
      "type": "string",
      "enum": ["Up","Down"]
    },
    "freestyle": {
      "type": "object",
      "properties": {
        "activityTimeInSeconds": { "type": "integer", "minimum": 0 },
        "activityTimeCountingDirection": { "type": "string", "enum": ["Up","Down"] },
        "activityTimeCondition": {
          "type": "object",
          "additionalProperties": {
            "type": "object",
            "properties": {
              "gte": { "type": "number" },
              "lte": { "type": "number" },
              "gt": { "type": "number" },
              "lt": { "type": "number" },
              "eq": { "type": "number" }
            },
            "additionalProperties": false
          }
        }
      },
      "additionalProperties": false
    },
    "victoryTypes": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": ["type","description","classificationPoints"],
        "properties": {
          "type": { "type": "string" },
          "description": { "type": "string" },
          "classificationPoints": {
            "type": "object",
            "required": ["winner","loser"],
            "properties": {
              "winner": {
                "oneOf": [
                  { "type": "integer" },
                  {
                    "type": "array",
                    "items": {
                      "type": "array",
                      "minItems": 2,
                      "maxItems": 2,
                      "prefixItems": [
                        { "type": "integer" },
                        {
                          "type": "object",
                          "required": ["when"],
                          "properties": {
                            "when": {
                              "type": "object",
                              "additionalProperties": {
                                "type": "object",
                                "properties": {
                                  "gte": { "type": "number" },
                                  "lte": { "type": "number" },
                                  "gt": { "type": "number" },
                                  "lt": { "type": "number" },
                                  "eq": { "type": "number" }
                                },
                                "additionalProperties": false
                              }
                            }
                          },
                          "additionalProperties": false
                        }
                      ]
                    }
                  }
                ]
              },
              "loser": {
                "oneOf": [
                  { "type": "integer" },
                  {
                    "type": "array",
                    "items": {
                      "type": "array",
                      "minItems": 2,
                      "maxItems": 2,
                      "prefixItems": [
                        { "type": "integer" },
                        {
                          "type": "object",
                          "required": ["when"],
                          "properties": {
                            "when": {
                              "type": "object",
                              "additionalProperties": {
                                "type": "object",
                                "properties": {
                                  "gte": { "type": "number" },
                                  "lte": { "type": "number" },
                                  "gt": { "type": "number" },
                                  "lt": { "type": "number" },
                                  "eq": { "type": "number" }
                                },
                                "additionalProperties": false
                              }
                            }
                          },
                          "additionalProperties": false
                        }
                      ]
                    }
                  }
                ]
              }
            },
            "additionalProperties": false
          },
          "condition": {
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "properties": {
                "gte": { "type": "number" },
                "lte": { "type": "number" },
                "gt": { "type": "number" },
                "lt": { "type": "number" },
                "eq": { "type": "number" }
              },
              "additionalProperties": false
            }
          }
        },
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false
}

=== 8biz/champ/protocol/rulesets/ruleset-default.json
{
  "metadata": {
    "name": "de-mannschaftskampf-2025",
    "description": "Deutsches Regelwerk für Mannschaftskämpfe",
    "languages": ["de"],
    "author": "Deutscher Ringer-Bund"
  },
  "periodTimesInSeconds": [180, 180],
  "periodTimeCountingDirection": "Down",
  "periodBreakTimeInSeconds": 30,
  "injuryTimeWithoutBloodInSeconds": 120,
  "injuryTimeWithBloodInSeconds": 240,
  "injuryTimeCountingDirection": "Up",
  "freestyle": {
    "activityTimeInSeconds": 30,
    "activityTimeCountingDirection": "Down",
    "activityTimeCondition": {
      "passivityCount": { "gt": 1 }
    }
  },
  "victoryTypes": [
    { "type": "SS", "description": "Schultersieg", "classificationPoints": { "winner": 4, "loser": 0 } },
    {
      "type": "TÜ",
      "description": "Technische Überlegenheit",
      "classificationPoints": { "winner": 4, "loser": 0 },
      "condition": { "scoreDifference": { "gte": 15 } }
    },
    {
      "type": "PS",
      "description": "Punktsieg",
      "classificationPoints": {
        "winner": [
          [3, { "when": { "scoreDifference": { "gte": 8, "lte": 14 } } }],
          [2, { "when": { "scoreDifference": { "gte": 3, "lte": 7 } } }],
          [1, { "when": { "scoreDifference": { "gte": 1, "lte": 2 } } }],
          [1, { "when": { "award5Difference": { "gt": 0 } } }],
          [1, { "when": { "award4Difference": { "gt": 0 } } }],
          [1, { "when": { "award2Difference": { "gt": 0 } } }],
          [1, { "when": { "lastAward": { "eq": 1 } } }]
        ],
        "loser": 0
      }
    },
    { "type": "AS", "description": "Aufgabesieg", "classificationPoints": { "winner": 4, "loser": 0 } },
    { "type": "DV", "description": "Disqualifikation durch 3 Verwarnungen", "classificationPoints": { "winner": 4, "loser": 0 }, "condition": { "cautionCount": { "gte": 3 } } },
    { "type": "DQ", "description": "Disqualifikation durch unfaires Verhalten", "classificationPoints": { "winner": 4, "loser": 0 } },
    { "type": "DSQ2", "description": "Beide Ringer disqualifiziert wegen unfairem Verhalten", "classificationPoints": { "winner": 0, "loser": 0 } },
    { "type": "KL", "description": "Kampfloser Sieg", "classificationPoints": { "winner": 4, "loser": 0 } },
    { "type": "ÜG", "description": "Übergewicht", "classificationPoints": { "winner": 4, "loser": 0 } }
  ]
}
